/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Borrow from './Borrow';

/**
 * The Book model module.
 * @module model/Book
 * @version 1.0
 */
class Book {
    /**
     * Constructs a new <code>Book</code>.
     * @alias module:model/Book
     */
    constructor() { 
        
        Book.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Book</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Book} obj Optional instance to populate.
     * @return {module:model/Book} The populated <code>Book</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Book();

            if (data.hasOwnProperty('author')) {
                obj['author'] = ApiClient.convertToType(data['author'], 'String');
            }
            if (data.hasOwnProperty('borrows')) {
                obj['borrows'] = ApiClient.convertToType(data['borrows'], [Borrow]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} author
 */
Book.prototype['author'] = undefined;

/**
 * @member {Array.<module:model/Borrow>} borrows
 */
Book.prototype['borrows'] = undefined;

/**
 * @member {Number} id
 */
Book.prototype['id'] = undefined;

/**
 * @member {String} title
 */
Book.prototype['title'] = undefined;






export default Book;

