/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Book from './Book';
import Person from './Person';

/**
 * The Borrow model module.
 * @module model/Borrow
 * @version 1.0
 */
class Borrow {
    /**
     * Constructs a new <code>Borrow</code>.
     * @alias module:model/Borrow
     */
    constructor() { 
        
        Borrow.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Borrow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Borrow} obj Optional instance to populate.
     * @return {module:model/Borrow} The populated <code>Borrow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Borrow();

            if (data.hasOwnProperty('book')) {
                obj['book'] = Book.constructFromObject(data['book']);
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('person')) {
                obj['person'] = Person.constructFromObject(data['person']);
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Book} book
 */
Borrow.prototype['book'] = undefined;

/**
 * @member {Date} endTime
 */
Borrow.prototype['endTime'] = undefined;

/**
 * @member {Number} id
 */
Borrow.prototype['id'] = undefined;

/**
 * @member {module:model/Person} person
 */
Borrow.prototype['person'] = undefined;

/**
 * @member {Date} startTime
 */
Borrow.prototype['startTime'] = undefined;






export default Borrow;

