/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.BookDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookDto', function() {
    it('should create an instance of BookDto', function() {
      // uncomment below and update the code to test BookDto
      //var instance = new ApiDocumentation.BookDto();
      //expect(instance).to.be.a(ApiDocumentation.BookDto);
    });

    it('should have the property author (base name: "author")', function() {
      // uncomment below and update the code to test the property author
      //var instance = new ApiDocumentation.BookDto();
      //expect(instance).to.be();
    });

    it('should have the property bookId (base name: "bookId")', function() {
      // uncomment below and update the code to test the property bookId
      //var instance = new ApiDocumentation.BookDto();
      //expect(instance).to.be();
    });

    it('should have the property borrows (base name: "borrows")', function() {
      // uncomment below and update the code to test the property borrows
      //var instance = new ApiDocumentation.BookDto();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new ApiDocumentation.BookDto();
      //expect(instance).to.be();
    });

  });

}));
