/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthenticationDto from './model/AuthenticationDto';
import BookDto from './model/BookDto';
import BorrowDto from './model/BorrowDto';
import ModelAndView from './model/ModelAndView';
import PersonDto from './model/PersonDto';
import View from './model/View';
import BasicErrorControllerApi from './api/BasicErrorControllerApi';
import BookControllerApi from './api/BookControllerApi';
import BorrowControllerApi from './api/BorrowControllerApi';
import LoginControllerApi from './api/LoginControllerApi';
import PersonControllerApi from './api/PersonControllerApi';


/**
* Api Documentation.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new ApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthenticationDto model constructor.
     * @property {module:model/AuthenticationDto}
     */
    AuthenticationDto,

    /**
     * The BookDto model constructor.
     * @property {module:model/BookDto}
     */
    BookDto,

    /**
     * The BorrowDto model constructor.
     * @property {module:model/BorrowDto}
     */
    BorrowDto,

    /**
     * The ModelAndView model constructor.
     * @property {module:model/ModelAndView}
     */
    ModelAndView,

    /**
     * The PersonDto model constructor.
     * @property {module:model/PersonDto}
     */
    PersonDto,

    /**
     * The View model constructor.
     * @property {module:model/View}
     */
    View,

    /**
    * The BasicErrorControllerApi service constructor.
    * @property {module:api/BasicErrorControllerApi}
    */
    BasicErrorControllerApi,

    /**
    * The BookControllerApi service constructor.
    * @property {module:api/BookControllerApi}
    */
    BookControllerApi,

    /**
    * The BorrowControllerApi service constructor.
    * @property {module:api/BorrowControllerApi}
    */
    BorrowControllerApi,

    /**
    * The LoginControllerApi service constructor.
    * @property {module:api/LoginControllerApi}
    */
    LoginControllerApi,

    /**
    * The PersonControllerApi service constructor.
    * @property {module:api/PersonControllerApi}
    */
    PersonControllerApi
};
