/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.BookControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookControllerApi', function() {
    describe('addBookUsingPOST', function() {
      it('should call addBookUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addBookUsingPOST
        //instance.addBookUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBookUsingDELETE', function() {
      it('should call deleteBookUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteBookUsingDELETE
        //instance.deleteBookUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findBooksUsingGET', function() {
      it('should call findBooksUsingGET successfully', function(done) {
        //uncomment below and update the code to test findBooksUsingGET
        //instance.findBooksUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findByPersonIdIsNotNullUsingGET', function() {
      it('should call findByPersonIdIsNotNullUsingGET successfully', function(done) {
        //uncomment below and update the code to test findByPersonIdIsNotNullUsingGET
        //instance.findByPersonIdIsNotNullUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBookUsingGET', function() {
      it('should call getBookUsingGET successfully', function(done) {
        //uncomment below and update the code to test getBookUsingGET
        //instance.getBookUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBooksUsingGET', function() {
      it('should call getBooksUsingGET successfully', function(done) {
        //uncomment below and update the code to test getBooksUsingGET
        //instance.getBooksUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateBookUsingPUT', function() {
      it('should call updateBookUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateBookUsingPUT
        //instance.updateBookUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
