/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.BorrowControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BorrowControllerApi', function() {
    describe('addBorrowUsingPOST', function() {
      it('should call addBorrowUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addBorrowUsingPOST
        //instance.addBorrowUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findAllUsingGET', function() {
      it('should call findAllUsingGET successfully', function(done) {
        //uncomment below and update the code to test findAllUsingGET
        //instance.findAllUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findBorrowByBookIdUsingGET', function() {
      it('should call findBorrowByBookIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test findBorrowByBookIdUsingGET
        //instance.findBorrowByBookIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findBorrowByPersonIdUsingGET', function() {
      it('should call findBorrowByPersonIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test findBorrowByPersonIdUsingGET
        //instance.findBorrowByPersonIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findBorrowByStartTimeAndEndTimeIsNotNullUsingGET', function() {
      it('should call findBorrowByStartTimeAndEndTimeIsNotNullUsingGET successfully', function(done) {
        //uncomment below and update the code to test findBorrowByStartTimeAndEndTimeIsNotNullUsingGET
        //instance.findBorrowByStartTimeAndEndTimeIsNotNullUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findBorrowByStartTimeIsNotNullAndEndTimeIsNullUsingGET', function() {
      it('should call findBorrowByStartTimeIsNotNullAndEndTimeIsNullUsingGET successfully', function(done) {
        //uncomment below and update the code to test findBorrowByStartTimeIsNotNullAndEndTimeIsNullUsingGET
        //instance.findBorrowByStartTimeIsNotNullAndEndTimeIsNullUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findByAuthorOrTitleContainingUsingGET', function() {
      it('should call findByAuthorOrTitleContainingUsingGET successfully', function(done) {
        //uncomment below and update the code to test findByAuthorOrTitleContainingUsingGET
        //instance.findByAuthorOrTitleContainingUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('nowBorrowedBooksUsingGET', function() {
      it('should call nowBorrowedBooksUsingGET successfully', function(done) {
        //uncomment below and update the code to test nowBorrowedBooksUsingGET
        //instance.nowBorrowedBooksUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('returnBookUsingPUT', function() {
      it('should call returnBookUsingPUT successfully', function(done) {
        //uncomment below and update the code to test returnBookUsingPUT
        //instance.returnBookUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('returnesBorrowesUsingGET', function() {
      it('should call returnesBorrowesUsingGET successfully', function(done) {
        //uncomment below and update the code to test returnesBorrowesUsingGET
        //instance.returnesBorrowesUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
